### PR TITLE
scroll animation added

### PR DESCRIPTION
**Pull request by ghost**
Here is the work I did
- #13 

https://user-images.githubusercontent.com/83635276/206632821-b1f42225-13a4-4423-929e-7add6cc3398e.mp4

### CODE REVIEW

**Review by Komachian — APPROVED** [review]
Good job 👍🏽

**Comment by Dibyendu303** [comment]
Hey @Komachian , I think we should add the slide effect to each image individually rather than the whole component. Otherwise it will not look good when viewed on a mobile screen. Can I show you a sample ?

**Comment by Komachian** [comment]
Hmm. I'll have a look at the sample.

**Comment by Dibyendu303** [comment]
Here @Komachian , have a look at it.

https://user-images.githubusercontent.com/66685553/206673120-1159592a-8280-48b6-9ed3-907db7b46291.mp4

**Comment by Komachian** [comment]
Looks good! But can you keep the animation for only while scrolling down and keep it static while scrolling up?

**Comment by Dibyendu303** [comment]
@Komachian Something like this:

https://user-images.githubusercontent.com/66685553/206686645-9743492c-b082-44c6-a4a5-a2efbeb633f4.mp4

**Comment by Komachian** [comment]
Create a PR, I'll give you 5 points for this Enhancement!

**Comment by Dibyendu303** [comment]
@Komachian Submitted a PR #21

**Pull request merged**
