### PR TITLE
added the gallery page

### PR DESCRIPTION
**Pull request by Adittya-Gupta**
Solved issue #9 
Here are the pictures of the implementation
image
image
image

### CODE REVIEW

**Comment by Komachian** [comment]
Nicely done. However, I can see that the number of images displayed for each event is fixed at 6 images currently. In our case though, the number of images could vary substantially.

**Comment by Adittya-Gupta** [comment]
But if there are more than 6 images how do you want the images to be oriented because in the issue it was shown only for 6 images

**Comment by Komachian** [comment]
Basically, display the images in such a way as to maintain their native aspect ratio. Here's an example with more photos -
image

**Comment by Adittya-Gupta** [comment]
image
will It be okay like this?

**Comment by Komachian** [comment]
Just take a look at this, https://www.w3schools.com/howto/howto_js_image_grid.asp

**Comment by Adittya-Gupta** [comment]
ya I made using this only. The problem is the number of images in your website is not fixed so I cannot make it exactly like this

**Comment by Komachian** [comment]
Hmm, a great attempt nonetheless. I'm merging this PR and awarding **10 points** to your total!

**Review by Komachian — APPROVED** [review]

**Pull request merged**
